// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeybhgybbcojweuezyvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpleWJoZ3liYmNvandldWV6eXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDU3OTksImV4cCI6MjA1NDY4MTc5OX0.u6BgQtpN-oM2Zo2Q9EfkpbyLq38ajBOyOtGMcklInLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);